### ISSUE TITLE
[Question] How to decorate all functions in a module?

### ISSUE THREAD

**Issue by aspett** [arjan/decorator#15]
I'm trying to use this library to decorate every function in a module. My current strategy for doing this is using an `on_definition` hook, and `put_attribute`'ing the required parameters. This appears to be working *nearly*. It has some trouble with multi-clause functions; especially with function headers.

After banging my head against this for a few hours, I thought it might just be better to ask if there's an easier way to decorate every function. Thanks!

**Comment by arjan** [comment]
This is an interesting question. I think this could be implemented using a `decorate_all` attribute:

```
defmodule Foo do
      use MyDecorator
      @decorate_all some_function(:foo)
end
```

Internally I would check for this attribute and decorate all `def`s based on it.

**Comment by aspett** [comment]
This would be very helpful for me. Honestly, I struggle to get my head around this codebase, though.

**Comment by ludwikbukowski** [comment]
++

**Comment by aspett** [comment]
@ludwikbukowski I made progress here: https://github.com/arjan/decorator/pull/16 but it breaks function headers at the moment. Not sure how to fix that yet

**Comment by arjan** [comment]
@aspett I merged an implementation similar to yours. I believe the issue with function headers will be dealt with in #18, so separate from this.
