### ISSUE TITLE
Release master

### ISSUE THREAD

**Issue by aspett** [arjan/decorator#30]
Hey. Just wondering if there was something in particular holding you back from releasing what's currently in master to hex? Cheers!

**Comment by arjan** [comment]
Not really actually, thanks for the headsup, I'll see to this today.

**Comment by arjan** [comment]
Done!

**Comment by arjan** [comment]
https://hex.pm/packages/decorator/1.3.0

**Comment by aspett** [comment]
Awesome! Thanks @arjan
