### ISSUE TITLE
Imperative form?

### ISSUE THREAD

**Issue by arjan** [arjan/decorator#6]
Looking at the [Erlang counterpart](https://github.com/chrisavl/erlang_decorators/blob/master/test/decorator_test.erl), I see they use the `@decorate` annotation, instead of `@decorator` that we use. `@decorate` is maybe a bit more clear, given that's an imperative, instead of a noun. 

`@decorator` maybe implies that we are defining a decorator, while in fact we are saying that we want to apply the decorator to the function.

@vic what do you think?

**Comment by vic** [comment]
```
@decorator maybe implies that we are defining a decorator, while in fact we are saying that we want to apply the decorator to the function.
```

Yep, I'd go with `@decorate` as you are applying a decorator to next function def.

**Comment by arjan** [comment]
Done!

**Comment by arjan** [comment]
I think I should release 1.0 now, because I'm not going to change the API anymore probably.
